### ISSUE TITLE
Something Funky with Unloading Passengers

### ISSUE THREAD

**Issue by mpdesantis** [ArthurAtangana/SYSC3303A_Project#90] opened 2024-03-24 17:44 UTC
After adding the extra fault column to the Parser, which was super simple and I didn't expect to add any headache, I seemed to have unlocked a bunch of errors. Traced around system messages for a few hours, but I'm not sure quite what is going on. 

Initially, there was a fault set to `null` somewhere that was preventing a SendPassengersCommand from ever being sent, meaning that elevators NEVER stopped lololol. Chased that around and changed it to `Fault.NONE` in commit 55ef030. 

Then the prints on the elevator were firing like crazy because of more nulls popping up in system messages, so suppressed those in commit c8bfce0.

Now it looks like, once an Elevator loads a passenger, they can't move. I'm not sure the issue, and I've exhausted my time chasing it. I think it might be something to do with all these mathematical set operations (eg. union, merge) maybe getting thrown because they have an extra field to deal with that is mismatching things. Not sure though!

I won't issue a PR, but if people could pull down `develop/latest` and compare it with `develop/parser-faults`, that would be great. Thanks!

**Comment by orselane** [comment] 2024-03-24 19:21
Print suppression is good, null fault needs to stay. The problem is the "wildcard" behavior is not working with union contains... It's a really weird bug where it doesn't look like its making use of the equals method. I'm looking into it.

The fix of setting it to Fault.None will ignore all fault carrying passengers -> null would grab any type if it worked.

**Comment by orselane** [comment] 2024-03-24 19:23
For the load and no move, its honestly probably related to changing it off the wildcard. It ensured parity with old behavior (if equals got called properly)

**Comment by orselane** [comment] 2024-03-24 20:01
Fixed in your branch, hope you don't mind. I didn't know how to reproduce it outside of your branch at the time.

(Fix had to do with a missing hashCode method override to pair with the equals override)

**Closed as completed by orselane** 2024-03-24 20:01 UTC
